apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: cncamp-golang
spec:
  type: git
  params:
    - name: url
      value: https://github.com/cncamp/golang.git
    - name: revision
      value: master
  secrets:
    - fieldName: authToken
      secretName: github-secrets
      secretKey: token
---
apiVersion: v1
kind: Secret
metadata:
  name: github-secrets
type: Opaque
data:
  token: changeme # in base64 encoded form
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: cncamp-test-image
spec:
  type: image
  params:
    - name: url
      value: cncamp/test
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: test-cluster
spec:
  type: cluster
  params:
    - name: url
      value: https://192.168.34.2:6443
    - name: username
      value: kubernetes-admin
  secrets:
    - fieldName: token
      secretKey: tokenKey
      secretName: target-cluster-secrets
    - fieldName: cadata
      secretKey: cadataKey
      secretName: target-cluster-secrets
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-auth
type: Opaque
stringData: 
  config.json: |-
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "auth": "changeme"
        }
      }
    }
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cncamp-sa
secrets:
- name: docker-auth