apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-system
  name: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
        - name: webhook
          image: cncamp/authn-webhook:v1.0
---
apiVersion: v1
kind: Service
metadata:
  name: webhook
  namespace: kube-system
spec:
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: webhook
